### PR TITLE
Fixed issue #103 where GET /api/mod/<mod_id> was not returning the

### PR DESCRIPTION
**Pull request by Deathnerd**
"updated" field from the database by adding an item in the dictionary
returned by mod_info.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
I'm going to hold off on merging this for now until I have a chance to test it. I know of some problems that have affected JSON serialization of date/time.

**Comment by Deathnerd** [comment]
Ah. I wasn't aware there was a problem serializing the SQLAlchemy DateTime column. I didn't have time to test this at all (bad Deathnerd, I know)

**Comment by oharaandrew314** [comment]
This addition would be nice so that TinkerTime can show the correct date when it updates a mod.  Maybe I'll test this out when I get the chance.

**Comment by SirCmpwn** [comment]
Sorry, I just forgot about this PR. I'll test it and merge it later today.

**Comment by oharaandrew314** [comment]
Thanks!

**Comment by SirCmpwn** [comment]
Got this exception when testing:

    127.0.0.1 - - [29/Jun/2015 14:50:09] "GET /api/mod/231 HTTP/1.0" 500 -
    Traceback (most recent call last):
      File "/home/sircmpwn/sources/KerbalStuff/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/home/sircmpwn/sources/KerbalStuff/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/home/sircmpwn/sources/KerbalStuff/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/home/sircmpwn/sources/KerbalStuff/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
        raise value
      File "/home/sircmpwn/sources/KerbalStuff/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/home/sircmpwn/sources/KerbalStuff/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/home/sircmpwn/sources/KerbalStuff/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/home/sircmpwn/sources/KerbalStuff/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
        raise value
      File "/home/sircmpwn/sources/KerbalStuff/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/sircmpwn/sources/KerbalStuff/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/sircmpwn/sources/KerbalStuff/KerbalStuff/common.py", line 122, in wrapper
        return jsonify_wrap(result)
      File "/home/sircmpwn/sources/KerbalStuff/KerbalStuff/common.py", line 115, in jsonify_wrap
        jsonification = json.dumps(obj, default=CustomJSONEncoder)
      File "/usr/lib/python3.4/json/__init__.py", line 237, in dumps
        **kw).encode(obj)
      File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
        return _iterencode(o, 0)
    RuntimeError: maximum recursion depth exceeded

**Comment by oharaandrew314** [comment]
Fun stuff.  I might take a look at this later, but it's not really a priority for me.

**Pull request closed without merging**
